/* Lo que lee el repartidor, en los dos idiomas.

   Aquí el inglés pesa menos que en la app de cliente: la flota es de
   Buenaventura. Pero un repartidor que no lee bien español existe, y
   dejarle la app a medias sería peor que no ofrecerla.

   El tono es distinto al del cliente a propósito. Al cliente se le
   vende; al repartidor se le informa. "Estás en línea", no "¡Ya estás
   listo para ganar dinero!". */

export const TEXTOS = {
  es: {
    comun: {
      guardar: 'Guardar',
      guardando: 'Guardando…',
      cancelar: 'Cancelar',
      cerrar: 'Cerrar',
      listo: 'Listo',
      volver: 'Volver',
      minutos: 'min',
      km: 'km',
      opcional: 'opcional',
      entregas: 'Entregas',
      calificacion: 'Calificación',
    },

    nav: {
      inicio: 'Inicio',
      ganancias: 'Ganancias',
      entregas: 'Entregas',
      cuenta: 'Cuenta',
    },

    inicio: {
      hola: 'Hola, {nombre}',
      ganadoHoy: 'GANADO HOY',
      enLinea: 'Estás en línea',
      enLineaSub: 'Recibiendo pedidos en {zona}',
      fueraDeLinea: 'Estás fuera de línea',
      fueraDeLineaSub: 'No te llegan pedidos mientras estés así',
      entregasHoy: 'Entregas hoy',
      enCurso: 'En curso',
      activaAlertas: 'Activa las alertas',
      activaAlertasSub: 'Te avisamos apenas entre un pedido',
      activar: 'Activar',
      sinPedidos: 'Sin pedidos por ahora',
      sinPedidosSub: 'Te avisamos apenas entre uno cerca de ti.',
      nuevoPedido: 'Nuevo pedido',
      aceptar: 'Aceptar',
      rechazar: 'Rechazar',
      simulador: 'Simulador de pedidos',
      buscandoPedidos: 'Buscando pedidos cerca',
      buscandoPedidosSub: 'Estás en zona {zona}. Te avisamos apenas llegue uno.',
      conectarme: 'Conectarme',
      actívate: 'Actívate para recibir pedidos',
      entregaCompletada: 'Entrega completada',
      sumadosATuDia: '{monto} sumados a tu día',
      yaLoRecogi: 'Ya lo recogí',
      voyEnCamino: 'Voy en camino',
      entregado: 'Entregado',
    },

    entregas: {
      titulo: 'Entregas',
      subtitulo: 'Lo que llevas hoy y lo que ya entregaste.',
      activa: 'Activa',
      historial: 'Historial',
      vacio: 'Todavía no tienes entregas',
      vacioSub: 'Cuando aceptes un pedido aparecerá aquí.',
      recoger: 'RECOGER EN',
      entregar: 'ENTREGAR EN',
      llamarCliente: 'Llamar al cliente',
      recogido: 'Ya lo recogí',
      enCamino: 'Voy en camino',
      entregar_btn: 'Entregar',
      confirmarEntrega: 'Confirmar entrega',
      pinTexto: 'Pídele al cliente los cuatro números de su código.',
      pinError: 'Ese código no coincide. Te quedan {intentos} intentos.',
      pinBloqueado: 'Demasiados intentos. Llama a la oficina.',
      entregado: 'Entregado',
      solicitado: 'Solicitado',
      porRecoger: 'Por recoger',
      cancelado: 'Cancelado',
      marcarRecogido: 'Marcar recogido',
      marcarEntregado: 'Marcar entregado',
      activos: 'Activos',
      entregados: 'Entregados',
      sinActivas: 'Sin entregas activas',
      sinActivasSub: 'Los pedidos que aceptes aparecerán aquí con su paso a paso.',
      nadaAqui: 'Nada por aquí',
      nadaAquiSub: 'Prueba con otro filtro o búsqueda.',
      pinAyuda: '{nombre} tiene 4 dígitos en su app. Escríbelos aquí para cerrar la entrega.',
      elCliente: 'El cliente',
      verificando: 'Verificando…',
      borrar: 'Borrar',
      turboPrioritario: 'DOMIX TURBO · PRIORITARIO',
      nuevoPedidoMayus: 'NUEVO PEDIDO',
    },

    ganancias: {
      titulo: 'Ganancias',
      disponible: 'Disponible para retirar',
      seConsigna: 'Se consigna a tu {metodo} {cuenta}',
      registraCuenta: 'Registra tu cuenta de retiro en Cuenta',
      ganado: 'Ganado',
      retirado: 'Retirado',
      enCurso: 'En curso',
      tarifasSemana: 'Tarifas de la semana',
      propinas: 'Propinas',
      entregasSemana: 'Entregas de la semana',
      ganadoTotal: 'Ganado en total',
      misRetiros: 'Mis retiros',
      movimientos: 'Movimientos',
      sinMovimientos: 'Sin movimientos',
      sinMovimientosSub: 'Cuando completes entregas, tus pagos aparecerán aquí.',
      solicitarRetiro: 'Solicitar retiro',
      retiroEnCamino: 'Retiro en camino',
      pedidoEl: 'Pedido el {fecha}',
    },

    cuenta: {
      titulo: 'Cuenta',
      documentos: 'Documentos',
      deCuatro: '{n} de 4',
      miVehiculo: 'Mi vehículo',
      cuentaRetiros: 'Cuenta para retiros',
      zonaTrabajo: 'Zona de trabajo',
      horario: 'Horario preferido',
      ayuda: 'Ayuda y soporte',
      sinRegistrar: 'Sin registrar',
      sinDefinir: 'Sin definir',
      apariencia: 'Apariencia',
      claro: 'Claro',
      oscuro: 'Oscuro',
      idioma: 'Idioma',
      espanol: 'Español',
      ingles: 'English',
      cambiarRepartidor: 'Cambiar de repartidor',
      pie: 'Domix · Mensajería & Logística · Buenaventura',
      faltanDocs: 'Te faltan {n} documentos. Con todos aprobados te llegan más pedidos.',
      faltaUnDoc: 'Te falta 1 documento. Con todos aprobados te llegan más pedidos.',
    },
  },

  en: {
    comun: {
      guardar: 'Save',
      guardando: 'Saving…',
      cancelar: 'Cancel',
      cerrar: 'Close',
      listo: 'Done',
      volver: 'Back',
      minutos: 'min',
      km: 'km',
      opcional: 'optional',
      entregas: 'Deliveries',
      calificacion: 'Rating',
    },

    nav: {
      inicio: 'Home',
      ganancias: 'Earnings',
      entregas: 'Deliveries',
      cuenta: 'Account',
    },

    inicio: {
      hola: 'Hi, {nombre}',
      ganadoHoy: 'EARNED TODAY',
      enLinea: "You're online",
      enLineaSub: 'Taking orders in {zona}',
      fueraDeLinea: "You're offline",
      fueraDeLineaSub: 'No orders reach you while you are offline',
      entregasHoy: 'Deliveries today',
      enCurso: 'In progress',
      activaAlertas: 'Turn on alerts',
      activaAlertasSub: 'We ping you the moment an order comes in',
      activar: 'Turn on',
      sinPedidos: 'No orders right now',
      sinPedidosSub: "We'll alert you as soon as one comes up near you.",
      nuevoPedido: 'New order',
      aceptar: 'Accept',
      rechazar: 'Decline',
      simulador: 'Order simulator',
      buscandoPedidos: 'Looking for orders nearby',
      buscandoPedidosSub: "You're in {zona}. We'll alert you the moment one comes up.",
      conectarme: 'Go online',
      actívate: 'Go online to receive orders',
      entregaCompletada: 'Delivery completed',
      sumadosATuDia: '{monto} added to your day',
      yaLoRecogi: 'Picked it up',
      voyEnCamino: "I'm on the way",
      entregado: 'Delivered',
    },

    entregas: {
      titulo: 'Deliveries',
      subtitulo: "What you're carrying today and what you've delivered.",
      activa: 'Active',
      historial: 'History',
      vacio: 'No deliveries yet',
      vacioSub: 'Once you accept an order it shows up here.',
      recoger: 'PICK UP AT',
      entregar: 'DELIVER TO',
      llamarCliente: 'Call the customer',
      recogido: 'Picked it up',
      enCamino: "I'm on the way",
      entregar_btn: 'Deliver',
      confirmarEntrega: 'Confirm delivery',
      pinTexto: 'Ask the customer for the four digits of their code.',
      pinError: "That code doesn't match. {intentos} tries left.",
      pinBloqueado: 'Too many tries. Call the office.',
      entregado: 'Delivered',
      solicitado: 'Requested',
      porRecoger: 'To pick up',
      cancelado: 'Cancelled',
      marcarRecogido: 'Mark as picked up',
      marcarEntregado: 'Mark as delivered',
      activos: 'Active',
      entregados: 'Delivered',
      sinActivas: 'No active deliveries',
      sinActivasSub: 'Orders you accept show up here with their step by step.',
      nadaAqui: 'Nothing here',
      nadaAquiSub: 'Try another filter or search.',
      pinAyuda: '{nombre} has 4 digits in their app. Type them here to close the delivery.',
      elCliente: 'The customer',
      verificando: 'Checking…',
      borrar: 'Delete',
      turboPrioritario: 'DOMIX TURBO · PRIORITY',
      nuevoPedidoMayus: 'NEW ORDER',
    },

    ganancias: {
      titulo: 'Earnings',
      disponible: 'Available to withdraw',
      seConsigna: 'Paid to your {metodo} {cuenta}',
      registraCuenta: 'Add your payout account under Account',
      ganado: 'Earned',
      retirado: 'Withdrawn',
      enCurso: 'In progress',
      tarifasSemana: "This week's fares",
      propinas: 'Tips',
      entregasSemana: 'Deliveries this week',
      ganadoTotal: 'Earned in total',
      misRetiros: 'My withdrawals',
      movimientos: 'Movements',
      sinMovimientos: 'No movements',
      sinMovimientosSub: 'Once you complete deliveries, your payments show up here.',
      solicitarRetiro: 'Request withdrawal',
      retiroEnCamino: 'Withdrawal on the way',
      pedidoEl: 'Requested {fecha}',
    },

    cuenta: {
      titulo: 'Account',
      documentos: 'Documents',
      deCuatro: '{n} of 4',
      miVehiculo: 'My vehicle',
      cuentaRetiros: 'Payout account',
      zonaTrabajo: 'Work zone',
      horario: 'Preferred hours',
      ayuda: 'Help and support',
      sinRegistrar: 'Not set',
      sinDefinir: 'Not set',
      apariencia: 'Appearance',
      claro: 'Light',
      oscuro: 'Dark',
      idioma: 'Language',
      espanol: 'Español',
      ingles: 'English',
      cambiarRepartidor: 'Switch courier',
      pie: 'Domix · Courier & Logistics · Buenaventura',
      faltanDocs: 'You are missing {n} documents. With all of them approved you get more orders.',
      faltaUnDoc: 'You are missing 1 document. With all of them approved you get more orders.',
    },
  },
};
