/* Todo lo que el cliente lee, en los dos idiomas.

   Las dos versiones se escriben juntas a propósito: cuando quedan en
   archivos separados, una se actualiza y la otra se queda vieja sin que
   nadie lo note hasta que un pasajero del puerto ve media pantalla en
   español.

   El inglés no es traducción literal. "Que me traigan" no es "That they
   bring me": es "Get something". Se busca lo que diría la app en inglés,
   no lo que dice la española palabra por palabra. */

export const TEXTOS = {
  es: {
    comun: {
      desde: 'DESDE',
      cancelar: 'Cancelar',
      continuar: 'Continuar',
      volver: 'Volver',
      cerrar: 'Cerrar',
      guardar: 'Guardar',
      listo: 'Listo',
      cargando: 'Cargando…',
      reintentar: 'Reintentar',
      minutos: 'min',
      km: 'km',
      opcional: 'opcional',
    },

    nav: {
      inicio: 'Inicio',
      servicios: 'Servicios',
      actividad: 'Actividad',
      cuenta: 'Cuenta',
    },

    inicio: {
      enviar: 'Enviar',
      traer: 'Que me traigan',
      queEnvias: '¿Qué vas a enviar?',
      queNecesitas: '¿Qué necesitas?',
      despues: 'Después',
      paraTi: 'Para ti',
      atajos: 'Atajos',
      servicios: 'Servicios',
      masFormas: 'Más formas de usar Domix',
      pedidoEnCurso: 'PEDIDO EN CURSO',
      enProceso: 'En proceso',
      verTodos: 'Ver todos los servicios',
      guardarLugar: 'Guardar un lugar',
      turboTitulo: 'Domix Turbo',
      turboTexto: 'Tu envío primero en la fila, en menos de 20 minutos.',
      whatsappTitulo: 'Pide por WhatsApp',
      whatsappTexto: '315 792 4906 · te respondemos al instante.',
      lema1: 'Enviamos confianza,',
      lema2: 'entregamos soluciones.',
      cobertura: 'Cobertura en Buenaventura y zonas aledañas',
      confiables: 'Confiables',
      confiablesSub: 'Tu envío en buenas manos',
      rapidos: 'Rápidos',
      rapidosSub: 'Entregas oportunas',
      locales: 'Locales',
      localesSub: 'Conocemos cada rincón',
    },

    servicios: {
      titulo: 'Servicios',
      subtitulo: 'Todo lo que Domix mueve por ti en Buenaventura.',
      pedirAhora: 'Pedir ahora',
      prioritaria: 'Entrega prioritaria',
      turboLema1: 'Cuando no puede esperar,',
      turboLema2: 'va en Turbo.',
      turboDetalle: 'Primero en la fila y en menos de 20 minutos dentro de {km} km, por {precio} más.',
      negocioPregunta: '¿Tienes un negocio?',
      negocioTitulo1: 'Nosotros somos',
      negocioTitulo2: 'tu domiciliario.',
      negocioTexto: '¿Tienes una tienda virtual o negocio pero no tienes domiciliario? Nos encargamos de la entrega para que tú solo vendas.',
      negocioCta: 'Quiero que Domix entregue lo mío',
      hablar: '¿Prefieres hablar?',
      whatsappTitulo: 'Pide por WhatsApp',
      whatsappSub: '315 792 4906 · atención inmediata',
      mensajeria: 'Mensajería',
      mensajeriaDesc: 'Envíos de documentos, cartas y correspondencia',
      autorizacion_medica: 'Autorizaciones médicas',
      autorizacion_medicaDesc: 'Trámites rápidos y seguros en EPS y clínicas',
      encomienda: 'Encomiendas',
      encomiendaDesc: 'Envío de paquetes y mercancías a nivel local',
      domicilio: 'Domicilios',
      domicilioDesc: 'Restaurantes, tiendas virtuales, maquillaje y más',
      mandado: 'Mandados',
      mandadoDesc: 'Compras, pagos, recados y diligencias varias',
    },

    pedir: {
      titulo: 'Pedir un servicio',
      queServicio: '¿Qué necesitas?',
      recoger: '¿Dónde lo recogemos?',
      entregar: '¿A dónde va?',
      recogerCorto: 'Recogida',
      entregarCorto: 'Entrega',
      detalle: '¿Qué llevamos?',
      detallePista: 'Un sobre con documentos, una caja mediana…',
      tuNombre: 'Tu nombre',
      tuCelular: 'Tu celular',
      celularPista: 'Para avisarte cuando el repartidor esté en camino',
      turbo: 'Domix Turbo',
      turboDesc: 'Primero en la fila, en menos de 20 minutos',
      pedir: 'Pedir el servicio',
      pidiendo: 'Enviando tu pedido…',
      resumen: 'Resumen',
      distancia: 'Distancia',
      tiempo: 'Tiempo estimado',
      total: 'Total a pagar',
      pagoEfectivo: 'Pagas en efectivo al recibir',
      faltaRecoger: 'Dinos dónde recogemos.',
      faltaEntregar: 'Dinos a dónde va.',
      faltaNombre: 'Escribe tu nombre.',
      faltaCelular: 'Escribe tu celular para poder avisarte.',
      celularInvalido: 'Ese celular no parece completo.',
      errorEnvio: 'No pudimos enviar tu pedido. Intenta otra vez.',
      sinRegistro: 'Sin registro. Sin cuentas. Solo pide.',
      paso: 'Paso {n} de 2',
      donde: '¿De dónde a dónde?',
      confirmar: 'Confirma y pide',
      siguiente: 'Continuar',
      calculando: 'Calculando la ruta…',
      eligeDirecciones: 'Elige las dos direcciones y calculamos la distancia y el precio exacto.',
      tarifaMinima: 'Tarifa mínima {precio}.',
      tarifa: 'Tarifa',
      detalleOpcional: 'Detalles',
      detalleOpcionalPista: 'Qué es, referencias, hora preferida…',
      pagoEfectivoPill: 'Pago en efectivo',
      sinRegistroPill: 'Sin registro',
      respuestaPill: 'Respuesta inmediata',
      nocturno: 'Nocturno',
      pedirAhora: 'Pedir ahora',
    },

    direccion: {
      buscar: 'Busca una dirección o un barrio',
      recientes: 'Usados hace poco',
      enMapa: 'Marcar en el mapa',
      buscando: 'Buscando…',
      sinResultados: 'No encontramos ese lugar. Márcalo en el mapa.',
      confirmarPunto: 'Confirmar este punto',
      arrastraMapa: 'Mueve el mapa para poner el punto exacto',
      barrioSinMapa: 'Este barrio no está en el mapa. Márcalo para que el repartidor te encuentre.',
      usarUbicacion: 'Usar mi ubicación',
      ubicando: 'Ubicando…',
      noAparece: 'No aparece mi dirección, marcarla en el mapa',
      marcarDireccion: 'Marcar dirección',
      guardando: 'Guardando…',
    },

    actividad: {
      titulo: 'Actividad',
      subtitulo: 'Tus pedidos, en curso y entregados.',
      vacioTitulo: 'Todavía no has pedido nada',
      vacioTexto: 'Cuando pidas un servicio, aquí puedes seguirlo en vivo.',
      pedirAlgo: 'Pedir un servicio',
      enCurso: 'En curso',
      entregados: 'Entregados',
      consulta: 'Consulta tus pedidos',
      consultaTexto: 'Sin cuenta ni contraseña: usamos tu celular solo para encontrarlos.',
      verPedidos: 'Ver mis pedidos',
      recibido: 'Recibido',
      asignado: 'Asignado',
      recogido: 'Recogido',
      enCamino: 'En camino',
      entregado: 'Entregado',
      cancelado: 'Cancelado',
    },

    seguimiento: {
      titulo: 'Tu pedido',
      codigo: 'Código',
      buscando: 'Buscando repartidor',
      buscandoDesc: 'Estamos avisándole a los repartidores cerca de ti.',
      asignado: 'Repartidor asignado',
      asignadoDesc: 'Va en camino a recoger tu envío.',
      recogido: 'Envío recogido',
      recogidoDesc: 'Tu envío ya va en camino.',
      enCamino: 'En camino',
      enCaminoDesc: 'Llega en pocos minutos.',
      entregado: 'Entregado',
      entregadoDesc: 'Tu envío llegó a su destino.',
      cancelado: 'Cancelado',
      canceladoDesc: 'Este pedido fue cancelado.',
      tuRepartidor: 'Tu repartidor',
      llamar: 'Llamar',
      escribir: 'WhatsApp',
      tuCodigo: 'TU CÓDIGO DE ENTREGA',
      codigoTexto: 'Dile estos cuatro números al repartidor cuando te entregue. Solo así se cierra el pedido.',
      llegaEn: 'Llega en',
      noEncontrado: 'No encontramos ese pedido',
      noEncontradoTexto: 'Revisa el código o pídelo de nuevo.',
      recogerEn: 'RECOGER EN',
      entregarEn: 'ENTREGAR EN',
      tarifa: 'TARIFA',
      ayuda: 'Ayuda',
      pedirOtro: 'Pedir otro',
      tuRepartidorSub: 'Tu repartidor Domix',
      escribirWhatsapp: 'Escribir por WhatsApp',
    },

    cuenta: {
      titulo: 'Cuenta',
      subtitulo: 'Sin registro. Tus datos quedan solo en este teléfono.',
      misDatos: 'Mis datos',
      nombre: 'Nombre',
      celular: 'Celular',
      sinNombre: 'Sin escribir',
      apariencia: 'Apariencia',
      claro: 'Claro',
      oscuro: 'Oscuro',
      idioma: 'Idioma',
      espanol: 'Español',
      ingles: 'English',
      misLugares: 'Mis lugares',
      sinLugares: 'Todavía no has guardado ningún lugar.',
      ayuda: 'Ayuda y soporte',
      ayudaSub: 'Escríbenos por WhatsApp',
      acercaDe: 'Domix · Mensajería & Logística · Buenaventura',
      privacidad: 'No creamos cuentas ni guardamos tus datos en un servidor. Lo que escribes aquí queda en tu teléfono.',
      borrar: 'Borrar mis datos de este teléfono',
    },
  },

  en: {
    comun: {
      desde: 'FROM',
      cancelar: 'Cancel',
      continuar: 'Continue',
      volver: 'Back',
      cerrar: 'Close',
      guardar: 'Save',
      listo: 'Done',
      cargando: 'Loading…',
      reintentar: 'Try again',
      minutos: 'min',
      km: 'km',
      opcional: 'optional',
    },

    nav: {
      inicio: 'Home',
      servicios: 'Services',
      actividad: 'Activity',
      cuenta: 'Account',
    },

    inicio: {
      enviar: 'Send',
      traer: 'Get something',
      queEnvias: 'What are you sending?',
      queNecesitas: 'What do you need?',
      despues: 'Later',
      paraTi: 'For you',
      atajos: 'Shortcuts',
      servicios: 'Services',
      masFormas: 'More ways to use Domix',
      pedidoEnCurso: 'ACTIVE ORDER',
      enProceso: 'In progress',
      verTodos: 'See all services',
      guardarLugar: 'Save a place',
      turboTitulo: 'Domix Turbo',
      turboTexto: 'Your delivery first in line, in under 20 minutes.',
      whatsappTitulo: 'Order on WhatsApp',
      whatsappTexto: '315 792 4906 · we reply right away.',
      lema1: 'We carry trust,',
      lema2: 'we deliver solutions.',
      cobertura: 'Serving Buenaventura and nearby areas',
      confiables: 'Trusted',
      confiablesSub: 'Your delivery in good hands',
      rapidos: 'Fast',
      rapidosSub: 'On-time deliveries',
      locales: 'Local',
      localesSub: 'We know every corner',
    },

    servicios: {
      titulo: 'Services',
      subtitulo: 'Everything Domix moves for you in Buenaventura.',
      pedirAhora: 'Order now',
      prioritaria: 'Priority delivery',
      turboLema1: "When it can't wait,",
      turboLema2: 'it goes Turbo.',
      turboDetalle: 'First in line and under 20 minutes within {km} km, for {precio} more.',
      negocioPregunta: 'Run a business?',
      negocioTitulo1: 'We are your',
      negocioTitulo2: 'delivery team.',
      negocioTexto: "Have an online shop or a business but no one to deliver? We handle the delivery so you only have to sell.",
      negocioCta: 'I want Domix to deliver for me',
      hablar: 'Rather talk to someone?',
      whatsappTitulo: 'Order on WhatsApp',
      whatsappSub: '315 792 4906 · we answer right away',
      mensajeria: 'Courier',
      mensajeriaDesc: 'Documents, letters and correspondence',
      autorizacion_medica: 'Medical paperwork',
      autorizacion_medicaDesc: 'Fast, safe errands at clinics and health providers',
      encomienda: 'Parcels',
      encomiendaDesc: 'Packages and goods delivered across the city',
      domicilio: 'Deliveries',
      domicilioDesc: 'Restaurants, online shops, pharmacies and more',
      mandado: 'Errands',
      mandadoDesc: 'Shopping, payments and errands of any kind',
    },

    pedir: {
      titulo: 'Request a service',
      queServicio: 'What do you need?',
      recoger: 'Where do we pick it up?',
      entregar: 'Where is it going?',
      recogerCorto: 'Pickup',
      entregarCorto: 'Drop-off',
      detalle: 'What are we carrying?',
      detallePista: 'An envelope with documents, a medium box…',
      tuNombre: 'Your name',
      tuCelular: 'Your phone',
      celularPista: 'So we can tell you when the courier is on the way',
      turbo: 'Domix Turbo',
      turboDesc: 'First in line, in under 20 minutes',
      pedir: 'Request it',
      pidiendo: 'Sending your order…',
      resumen: 'Summary',
      distancia: 'Distance',
      tiempo: 'Estimated time',
      total: 'Total to pay',
      pagoEfectivo: 'You pay cash on delivery',
      faltaRecoger: 'Tell us where to pick it up.',
      faltaEntregar: 'Tell us where it goes.',
      faltaNombre: 'Enter your name.',
      faltaCelular: 'Enter your phone so we can reach you.',
      celularInvalido: 'That phone number looks incomplete.',
      errorEnvio: "We couldn't send your order. Please try again.",
      sinRegistro: 'No sign-up. No accounts. Just order.',
      paso: 'Step {n} of 2',
      donde: 'From where to where?',
      confirmar: 'Confirm and order',
      siguiente: 'Continue',
      calculando: 'Working out the route…',
      eligeDirecciones: 'Pick both addresses and we work out the exact distance and price.',
      tarifaMinima: 'Minimum fare {precio}.',
      tarifa: 'Fare',
      detalleOpcional: 'Details',
      detalleOpcionalPista: 'What it is, landmarks, preferred time…',
      pagoEfectivoPill: 'Cash on delivery',
      sinRegistroPill: 'No sign-up',
      respuestaPill: 'Instant reply',
      nocturno: 'Night rate',
      pedirAhora: 'Order now',
    },

    direccion: {
      buscar: 'Search an address or neighbourhood',
      recientes: 'Recently used',
      enMapa: 'Pick on the map',
      buscando: 'Searching…',
      sinResultados: "We couldn't find that place. Mark it on the map.",
      confirmarPunto: 'Confirm this spot',
      arrastraMapa: 'Move the map to set the exact spot',
      barrioSinMapa: "This neighbourhood isn't on the map. Mark it so the courier can find you.",
      usarUbicacion: 'Use my location',
      ubicando: 'Locating…',
      noAparece: "My address isn't listed, mark it on the map",
      marcarDireccion: 'Mark address',
      guardando: 'Saving…',
    },

    actividad: {
      titulo: 'Activity',
      subtitulo: 'Your orders, active and delivered.',
      vacioTitulo: "You haven't ordered anything yet",
      vacioTexto: 'Once you request a service, you can follow it live here.',
      pedirAlgo: 'Request a service',
      enCurso: 'Active',
      entregados: 'Delivered',
      consulta: 'Find your orders',
      consultaTexto: 'No account, no password: we only use your phone to look them up.',
      verPedidos: 'See my orders',
      recibido: 'Received',
      asignado: 'Assigned',
      recogido: 'Picked up',
      enCamino: 'On the way',
      entregado: 'Delivered',
      cancelado: 'Cancelled',
    },

    seguimiento: {
      titulo: 'Your order',
      codigo: 'Code',
      buscando: 'Finding a courier',
      buscandoDesc: "We're alerting couriers near you.",
      asignado: 'Courier assigned',
      asignadoDesc: 'On the way to pick it up.',
      recogido: 'Picked up',
      recogidoDesc: 'Your delivery is on its way.',
      enCamino: 'On the way',
      enCaminoDesc: 'Arriving in a few minutes.',
      entregado: 'Delivered',
      entregadoDesc: 'Your delivery arrived.',
      cancelado: 'Cancelled',
      canceladoDesc: 'This order was cancelled.',
      tuRepartidor: 'Your courier',
      llamar: 'Call',
      escribir: 'WhatsApp',
      tuCodigo: 'YOUR DELIVERY CODE',
      codigoTexto: 'Give these four digits to the courier on delivery. That is what closes the order.',
      llegaEn: 'Arrives in',
      noEncontrado: "We couldn't find that order",
      noEncontradoTexto: 'Check the code or place it again.',
      recogerEn: 'PICK UP AT',
      entregarEn: 'DELIVER TO',
      tarifa: 'FARE',
      ayuda: 'Help',
      pedirOtro: 'Order again',
      tuRepartidorSub: 'Your Domix courier',
      escribirWhatsapp: 'Message on WhatsApp',
    },

    cuenta: {
      titulo: 'Account',
      subtitulo: 'No sign-up. Your details stay on this phone.',
      misDatos: 'My details',
      nombre: 'Name',
      celular: 'Phone',
      sinNombre: 'Not set',
      apariencia: 'Appearance',
      claro: 'Light',
      oscuro: 'Dark',
      idioma: 'Language',
      espanol: 'Español',
      ingles: 'English',
      misLugares: 'My places',
      sinLugares: "You haven't saved any places yet.",
      ayuda: 'Help and support',
      ayudaSub: 'Message us on WhatsApp',
      acercaDe: 'Domix · Courier & Logistics · Buenaventura',
      privacidad: "We don't create accounts or keep your details on a server. What you type here stays on your phone.",
      borrar: 'Erase my details from this phone',
    },
  },
};
